# FROM golang:alpine
FROM frolvlad/alpine-miniconda3

# Install GO
RUN apk update
RUN apk add wget
RUN wget https://dl.google.com/go/go1.20.5.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.20.5.linux-amd64.tar.gz 
ENV PATH=$PATH:/usr/local/go/bin
RUN go version

WORKDIR /var/lib/benchmark

# Config Python
COPY benchmark-scripts/ann/requirements.txt /var/lib/benchmark/requirements.txt
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN pip3 install -r requirements.txt
RUN python3 -m pip install -r requirements.txt
ENV PYTHONUNBUFFERED=1

# Gemini support
COPY ./gsi/gemini.py ./
COPY ./gsi/swagger_client ./swagger_client

# Config GO benchmarker
COPY ./benchmarker ./
RUN go build -o benchmarker .

CMD [ "python", "./benchmark.py" ]

# copy benchmarking scripts last, so that when paramters are changed, the rest
# can be taken from cache
COPY benchmark-scripts/ann/benchmark.py /var/lib/benchmark/benchmark.py
COPY benchmark-scripts/src/functions.py /var/lib/benchmark/functions.py


