---
version: '3.4'
services:
  benchmark-ann:
    build: 
      context: ./
      dockerfile: Dockerfile-ann-gsi
    volumes:
      - $PWD/benchmark-data:/var/hdf5
      - $PWD/results:/var/lib/benchmark/results
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8084'
    - --scheme
    - http
    image: docker.io/semitechnologies/weaviate:1.19.8
    ports:
      - 8084:8084
    volumes:
      - $PWD/weaviate-data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      GOGC: 800
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'benchmark_node'
...
